[build]
  base = ""
  publish = "dist"
  command = "npm run build"
  functions = "functions"

# For NetlifyCLI Development
[dev]
  framework = "#custom"
  command = "npm run dev"
  publish = "dist"
  port = 3000
  targetPort = 8080
  autoLaunch = false