[build]
  base = ""
  publish = "dist"
  command = "npm run build"
  functions = "functions"

# For NetlifyCLI Development
[dev]
  command = "npm run dev"
  publish = "dist"
  port = 3000
  functionsPort = 9000
  targetPort = 8080